"""Made the recipe_id column in Cart_ingredient_mapping nullable

Revision ID: 03e6ceb4c2e5
Revises: adcde99beecd
Create Date: 2026-08-22 22:38:09.732834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e6ceb4c2e5'
down_revision: Union[str, Sequence[str], None] = 'adcde99beecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_ingredient_mapping', 'recipe_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_ingredient_mapping', 'recipe_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
