"""Updated Foreign Key errors and optional parameters

Revision ID: 095a4f41dc61
Revises: c7da68e1bc8f
Create Date: 2026-07-19 17:27:41.572166

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "095a4f41dc61"
down_revision: Union[str, Sequence[str], None] = "c7da68e1bc8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_details", sa.Column("username", sa.VARCHAR(length=255), nullable=True)
    )
    op.drop_constraint(
        op.f("user_details_address_id_fkey"), "user_details", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "user_details",
        "address_details",
        ["address_id"],
        ["address_id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "user_payment_details",
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "user_payment_details",
        sa.Column("created_by", sa.VARCHAR(length=255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_payment_details", "created_by")
    op.drop_column("user_payment_details", "created_at")
    op.drop_constraint(
        op.f("user_details_address_id_fkey"), "user_details", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("user_details_address_id_fkey"),
        "user_details",
        "user_details",
        ["address_id"],
        ["user_id"],
        ondelete="CASCADE",
    )
    op.drop_column("user_details", "username")
    # ### end Alembic commands ###
