"""Added a new table UserCalendarPlanDetails to store the calendar dates for which recipes have been saved

Revision ID: 2e25ea9a718a
Revises: 8ca2bcfb0237
Create Date: 2026-08-19 22:00:59.402571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e25ea9a718a'
down_revision: Union[str, Sequence[str], None] = '8ca2bcfb0237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
