"""Added created by and created at column in helpfulreviews

Revision ID: 36f6016abf45
Revises: c93429b66106
Create Date: 2026-08-24 16:34:59.813537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36f6016abf45'
down_revision: Union[str, Sequence[str], None] = 'c93429b66106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('helpful_reviews', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('helpful_reviews', sa.Column('created_by', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('helpful_reviews', 'created_by')
    op.drop_column('helpful_reviews', 'created_at')
    # ### end Alembic commands ###
