"""Changed datatype for recipe_directions in recipedirectionsdetails

Revision ID: 522e02efe463
Revises: f31b9e2a7c1d
Create Date: 2026-07-25 14:29:34.920187

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "522e02efe463"
down_revision: Union[str, Sequence[str], None] = "f31b9e2a7c1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_details",
        sa.Column(
            "nutrition_details",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=False,
        ),
    )
    op.drop_column("recipe_details", "recipeDirections")
    op.add_column(
        "recipe_ingredient_mapping",
        sa.Column(
            "recipe_ingredient_mapping_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
    )
    op.add_column(
        "recipe_ingredient_mapping", sa.Column("recipe_item", sa.UUID(), nullable=False)
    )
    op.add_column(
        "recipe_ingredient_mapping",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "recipe_ingredient_mapping",
        sa.Column("created_by", sa.VARCHAR(length=255), nullable=False),
    )
    op.create_foreign_key(
        None,
        "recipe_ingredient_mapping",
        "recipe_item_details",
        ["recipe_item"],
        ["recipe_item_id"],
        ondelete="CASCADE",
    )
    op.drop_column("recipe_ingredient_mapping", "recipe_ingredient_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_ingredient_mapping",
        sa.Column(
            "recipe_ingredient_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("recipe_ingredient_mapping_recipe_item_fkey"),
        "recipe_ingredient_mapping",
        type_="foreignkey",
    )
    op.drop_column("recipe_ingredient_mapping", "created_by")
    op.drop_column("recipe_ingredient_mapping", "created_at")
    op.drop_column("recipe_ingredient_mapping", "recipe_item")
    op.drop_column("recipe_ingredient_mapping", "recipe_ingredient_mapping_id")
    op.add_column(
        "recipe_details",
        sa.Column(
            "recipeDirections",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("recipe_details", "nutrition_details")
    # ### end Alembic commands ###
