"""Changed property name for recipe item to recipe item id in recipeingredientsmapping

Revision ID: 63a61568ea99
Revises: 79b2daf1a653
Create Date: 2026-07-26 00:16:09.666671

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63a61568ea99"
down_revision: Union[str, Sequence[str], None] = "79b2daf1a653"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_ingredient_mapping",
        sa.Column("recipe_item_id", sa.UUID(), nullable=False),
    )
    op.drop_constraint(
        op.f("recipe_ingredient_mapping_recipe_item_fkey"),
        "recipe_ingredient_mapping",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "recipe_ingredient_mapping",
        "recipe_item_details",
        ["recipe_item_id"],
        ["recipe_item_id"],
        ondelete="CASCADE",
    )
    op.drop_column("recipe_ingredient_mapping", "recipe_item")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_ingredient_mapping",
        sa.Column("recipe_item", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("recipe_ingredient_mapping_recipe_item_id_fkey"),
        "recipe_ingredient_mapping",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("recipe_ingredient_mapping_recipe_item_fkey"),
        "recipe_ingredient_mapping",
        "recipe_item_details",
        ["recipe_item"],
        ["recipe_item_id"],
        ondelete="CASCADE",
    )
    op.drop_column("recipe_ingredient_mapping", "recipe_item_id")
    # ### end Alembic commands ###
