"""Added vegetarian value for recipedetails

Revision ID: 8090bc733698
Revises: aa5a18dd394e
Create Date: 2026-07-25 21:02:13.770266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8090bc733698'
down_revision: Union[str, Sequence[str], None] = 'aa5a18dd394e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('vegetarian', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_details', 'vegetarian')
    # ### end Alembic commands ###
