"""Added a new user favorites and bookmarked table removing just bookmarked table

Revision ID: 8ca2bcfb0237
Revises: 01c4d72829ea
Create Date: 2026-08-17 19:27:06.398850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ca2bcfb0237'
down_revision: Union[str, Sequence[str], None] = '01c4d72829ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bookmarked_faborites_details')
    op.drop_table('user_liked_details')
    op.drop_table('user_bookmarked_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bookmarked_details',
    sa.Column('user_bookmarked_details_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_details.recipe_id'], name=op.f('user_bookmarked_details_recipe_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], name=op.f('user_bookmarked_details_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_bookmarked_details_id', name=op.f('user_bookmarked_details_pkey'))
    )
    op.create_table('user_liked_details',
    sa.Column('user_lisked_details_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_details.recipe_id'], name=op.f('user_liked_details_recipe_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], name=op.f('user_liked_details_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_lisked_details_id', name=op.f('user_liked_details_pkey'))
    )
    op.create_table('user_bookmarked_faborites_details',
    sa.Column('user_bookmarked_details_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bookmarked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('favorites', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_details.recipe_id'], name=op.f('user_bookmarked_faborites_details_recipe_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], name=op.f('user_bookmarked_faborites_details_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_bookmarked_details_id', name=op.f('user_bookmarked_faborites_details_pkey'))
    )
    # ### end Alembic commands ###
