"""Added a new column description for recipe item details

Revision ID: a5c7e6ab8724
Revises: 0f6c2a1b9d4e
Create Date: 2026-08-23 13:02:15.718216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c7e6ab8724'
down_revision: Union[str, Sequence[str], None] = '0f6c2a1b9d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_item_details', sa.Column('item_description', sa.TEXT(), server_default=sa.text("'No description provided.'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_item_details', 'item_description')
    # ### end Alembic commands ###
