"""Changed property name for recipe item to recipe item id in recipeingredientsmapping

Revision ID: a8185626e403
Revises: 63a61568ea99
Create Date: 2026-07-26 15:50:17.514556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8185626e403'
down_revision: Union[str, Sequence[str], None] = '63a61568ea99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('time_to_cook', sa.VARCHAR(length=50), server_default=sa.text("'0 mins'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_details', 'time_to_cook')
    # ### end Alembic commands ###
