"""Changed datatype for recipe directions

Revision ID: aa5a18dd394e
Revises: 522e02efe463
Create Date: 2026-07-25 20:49:10.797319

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa5a18dd394e"
down_revision: Union[str, Sequence[str], None] = "522e02efe463"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipe_directions_details",
        "recipe_direction",
        existing_type=sa.TEXT(),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=False,
        postgresql_using="ARRAY[recipe_direction]",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipe_directions_details",
        "recipe_direction",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=sa.TEXT(),
        existing_nullable=False,
        postgresql_using="array_to_string(recipe_direction, ' || ')",
    )
    # ### end Alembic commands ###
