"""Changes to UserDetails

Revision ID: ad88796ebae6
Revises: b159ddb26ccb
Create Date: 2026-07-19 22:35:03.632937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad88796ebae6'
down_revision: Union[str, Sequence[str], None] = 'b159ddb26ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_details', 'address_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_details', 'address_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
