"""Added an optional recipe_id field in ingredient cart mapping table

Revision ID: adcde99beecd
Revises: 0d5a41a4737e
Create Date: 2026-08-21 22:59:20.353210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adcde99beecd'
down_revision: Union[str, Sequence[str], None] = '0d5a41a4737e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_ingredient_mapping', sa.Column('recipe_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'cart_ingredient_mapping', 'recipe_details', ['recipe_id'], ['recipe_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_ingredient_mapping', type_='foreignkey')
    op.drop_column('cart_ingredient_mapping', 'recipe_id')
    # ### end Alembic commands ###
