"""Added a new column to recipedetails for tips

Revision ID: b6ca3cda0e93
Revises: d9bc6b959135
Create Date: 2026-07-29 17:09:03.943990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6ca3cda0e93'
down_revision: Union[str, Sequence[str], None] = 'd9bc6b959135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('tips', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_details', 'tips')
    # ### end Alembic commands ###
