"""Created a new table to map recipe and ingredients and also add fields to recipe details

Revision ID: b86e0a3fb766
Revises: e642c083864f
Create Date: 2026-07-25 10:18:11.899948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86e0a3fb766'
down_revision: Union[str, Sequence[str], None] = 'e642c083864f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('kit_price', sa.DOUBLE_PRECISION(), nullable=False))
    op.add_column('recipe_details', sa.Column('no_of_people_served', sa.INTEGER(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_details', 'no_of_people_served')
    op.drop_column('recipe_details', 'kit_price')
    # ### end Alembic commands ###
