"""create first revision for all tables

Revision ID: c7da68e1bc8f
Revises: 
Create Date: 2026-07-18 12:19:57.412504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7da68e1bc8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_details',
    sa.Column('address_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('contact_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address_line_1', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address_line_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=False),
    sa.Column('state_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('pincode', sa.VARCHAR(length=255), nullable=False),
    sa.Column('country', sa.VARCHAR(length=255), nullable=False),
    sa.Column('google_maps_link', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('category_details',
    sa.Column('category_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category_description', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('ingredient_details',
    sa.Column('ingredient_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ingredient_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ingredient_min_quantity', sa.INTEGER(), nullable=False),
    sa.Column('ingredient_quantity_metric', sa.VARCHAR(length=15), nullable=False),
    sa.Column('price_per_unit', sa.FLOAT(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id'),
    sa.UniqueConstraint('ingredient_name')
    )
    op.create_table('payment_mode_details',
    sa.Column('payment_mode_id', sa.UUID(), nullable=False),
    sa.Column('payment_mode_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('payment_mode_id'),
    sa.UniqueConstraint('payment_mode_name')
    )
    op.create_table('regions_details',
    sa.Column('region_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('region_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('region_description', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('region_id'),
    sa.UniqueConstraint('region_name')
    )
    op.create_table('user_type_details',
    sa.Column('user_type_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_type_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_type_description', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_type_id'),
    sa.UniqueConstraint('user_type_name')
    )
    op.create_table('recipe_details',
    sa.Column('recipe_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipe_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('number_of_total_visits', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('recipeDirections', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category_details.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions_details.region_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id'),
    sa.UniqueConstraint('recipe_name')
    )
    op.create_table('user_details',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('user_type_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['user_details.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_type_id'], ['recipe_details.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('cart_details',
    sa.Column('cart_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('user_bookmarked_details',
    sa.Column('user_bookmarked_details_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_details.recipe_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_bookmarked_details_id')
    )
    op.create_table('user_most_viewed_recipes',
    sa.Column('user_most_viewed_recipes_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('number_of_visits', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_details.recipe_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_most_viewed_recipes_id')
    )
    op.create_table('user_payment_details',
    sa.Column('user_payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_mode_id', sa.UUID(), nullable=False),
    sa.Column('upi_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('card_number', sa.VARCHAR(length=255), nullable=True),
    sa.Column('card_holder_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_payment_expiry_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_mode_id'], ['payment_mode_details.payment_mode_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_payment_id')
    )
    op.create_table('cart_ingredient_mapping',
    sa.Column('cart_ingredient_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart_details.cart_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_details.ingredient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_ingredient_id')
    )
    op.create_table('cart_recipe_mapping',
    sa.Column('cart_recipe_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart_details.cart_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_details.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_recipe_id')
    )
    op.create_table('order_details',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_payment_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_payment_id'], ['user_payment_details.user_payment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_ingredient_mapping',
    sa.Column('order_ingredient_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_details.ingredient_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order_details.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_ingredient_id')
    )
    op.create_table('order_recipe_mapping',
    sa.Column('order_recipe_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_details.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_details.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_recipe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_recipe_mapping')
    op.drop_table('order_ingredient_mapping')
    op.drop_table('order_details')
    op.drop_table('cart_recipe_mapping')
    op.drop_table('cart_ingredient_mapping')
    op.drop_table('user_payment_details')
    op.drop_table('user_most_viewed_recipes')
    op.drop_table('user_bookmarked_details')
    op.drop_table('cart_details')
    op.drop_table('user_details')
    op.drop_table('recipe_details')
    op.drop_table('user_type_details')
    op.drop_table('regions_details')
    op.drop_table('payment_mode_details')
    op.drop_table('ingredient_details')
    op.drop_table('category_details')
    op.drop_table('address_details')
    # ### end Alembic commands ###
