"""Added a new table HelpfulReviews to mark which reviews have been helpful for users

Revision ID: c93429b66106
Revises: dda1a6f3c7b9
Create Date: 2026-08-24 12:13:32.730202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93429b66106'
down_revision: Union[str, Sequence[str], None] = 'dda1a6f3c7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_helpful_reviews', 'helpful_reviews', ['recipe_review_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_helpful_reviews', 'helpful_reviews', type_='unique')
    # ### end Alembic commands ###
