"""Changed the type for tips in recipe details

Revision ID: d50779d5a836
Revises: a5c7e6ab8724
Create Date: 2026-08-23 14:10:06.694457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50779d5a836'
down_revision: Union[str, Sequence[str], None] = 'a5c7e6ab8724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
