"""Updated new search vector table for the ingredients

Revision ID: d8d5d3dc1f21
Revises: e075e70d6438
Create Date: 2026-09-03 20:17:43.049489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8d5d3dc1f21'
down_revision: Union[str, Sequence[str], None] = 'e075e70d6438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_search_documents_document'), table_name='recipe_search_documents', postgresql_using='gin')
    op.drop_table('recipe_search_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_search_documents',
    sa.Column('recipe_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document', postgresql.TSVECTOR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_details.recipe_id'], name=op.f('recipe_search_documents_recipe_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', name=op.f('recipe_search_documents_pkey'))
    )
    op.create_index(op.f('ix_recipe_search_documents_document'), 'recipe_search_documents', ['document'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
