"""Added properties for recipe details and created a new table for reviews

Revision ID: d9bc6b959135
Revises: ff361541f584
Create Date: 2026-07-28 18:03:40.557159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9bc6b959135'
down_revision: Union[str, Sequence[str], None] = 'ff361541f584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('prep_time', sa.VARCHAR(length=50), server_default=sa.text("'0 mins'"), nullable=False))
    op.add_column('recipe_details', sa.Column('cook_time', sa.VARCHAR(length=50), server_default=sa.text("'0 mins'"), nullable=False))
    op.add_column('recipe_details', sa.Column('difficulty_level', sa.VARCHAR(length=10), server_default=sa.text("'Easy'"), nullable=False))
    op.add_column('recipe_details', sa.Column('total_time', sa.VARCHAR(length=50), server_default=sa.text("'0 mins'"), nullable=False))
    op.add_column('recipe_details', sa.Column('features', postgresql.ARRAY(sa.VARCHAR(length=50)), server_default=sa.text("'{}'"), nullable=False))
    op.drop_column('recipe_details', 'time_to_cook')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('time_to_cook', sa.VARCHAR(length=50), server_default=sa.text("'0 mins'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('recipe_details', 'features')
    op.drop_column('recipe_details', 'total_time')
    op.drop_column('recipe_details', 'difficulty_level')
    op.drop_column('recipe_details', 'cook_time')
    op.drop_column('recipe_details', 'prep_time')
    # ### end Alembic commands ###
