"""Added a new column description for recipe item details

Revision ID: dda1a6f3c7b9
Revises: d50779d5a836
Create Date: 2026-08-23 14:12:26.508838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda1a6f3c7b9'
down_revision: Union[str, Sequence[str], None] = 'd50779d5a836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
