"""Updated Foreign Key error in UserDetails

Revision ID: e4043c6c6f00
Revises: 095a4f41dc61
Create Date: 2026-07-19 17:29:32.390437

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4043c6c6f00"
down_revision: Union[str, Sequence[str], None] = "095a4f41dc61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_details_user_type_id_fkey"), "user_details", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "user_details",
        "user_type_details",
        ["user_type_id"],
        ["user_type_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_details_user_type_id_fkey"), "user_details", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("user_details_user_type_id_fkey"),
        "user_details",
        "recipe_details",
        ["user_type_id"],
        ["recipe_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
