"""Added image url field for category and regions table

Revision ID: e642c083864f
Revises: 8b85db9ca9a8
Create Date: 2026-07-24 10:34:25.301969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e642c083864f'
down_revision: Union[str, Sequence[str], None] = '8b85db9ca9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_details', sa.Column('image_url', sa.VARCHAR(length=255), nullable=False))
    op.add_column('regions_details', sa.Column('image_url', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions_details', 'image_url')
    op.drop_column('category_details', 'image_url')
    # ### end Alembic commands ###
