"""Added a new table to store blacklisted tokens instead of redis

Revision ID: fd2664d21301
Revises: cc3eab973dbc
Create Date: 2026-08-25 21:27:20.201392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2664d21301'
down_revision: Union[str, Sequence[str], None] = 'cc3eab973dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_jwt_tokens', sa.Column('blacklisted_token_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('blacklisted_jwt_tokens', sa.Column('token_jti', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('blacklisted_jwt_tokens', 'jwt_id')
    op.drop_column('blacklisted_jwt_tokens', 'token')
    op.drop_column('blacklisted_jwt_tokens', 'token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_jwt_tokens', sa.Column('token_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.add_column('blacklisted_jwt_tokens', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('blacklisted_jwt_tokens', sa.Column('jwt_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('blacklisted_jwt_tokens', 'token_jti')
    op.drop_column('blacklisted_jwt_tokens', 'blacklisted_token_id')
    # ### end Alembic commands ###
