"""Added description and ratings column to recipe details

Revision ID: fd4791948fa6
Revises: a8185626e403
Create Date: 2026-07-26 18:18:51.930826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4791948fa6'
down_revision: Union[str, Sequence[str], None] = 'a8185626e403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('recipe_discription', sa.TEXT(), server_default=sa.text("'No description provided.'"), nullable=False))
    op.add_column('recipe_details', sa.Column('ratings', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_details', 'ratings')
    op.drop_column('recipe_details', 'recipe_discription')
    # ### end Alembic commands ###
