"""changed recipe description spelling

Revision ID: ff361541f584
Revises: fd4791948fa6
Create Date: 2026-07-27 12:37:30.749666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff361541f584'
down_revision: Union[str, Sequence[str], None] = 'fd4791948fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('recipe_description', sa.TEXT(), server_default=sa.text("'No description provided.'"), nullable=False))
    op.drop_column('recipe_details', 'recipe_discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_details', sa.Column('recipe_discription', sa.TEXT(), server_default=sa.text("'No description provided.'::text"), autoincrement=False, nullable=False))
    op.drop_column('recipe_details', 'recipe_description')
    # ### end Alembic commands ###
