from calendar import c


class ConstantsClass:
    invalid_access_token = "Invalid access token."

    user_signin_successful = "User has been signed in successfully."
    user_login_successful = "User has been logged in successfully."
    user_logout_successful = "User has been logged out successfully."
    user_already_exists = "User already exists."
    user_not_found = "User not found."
    password_updated_successfully = "Password updated successfully."
    token_expired = "Token has expired."
    token_not_expired = "Token is still valid."
    token_refresh_successful = "Token refreshed successfully."

    all_category_fetch_successful = "Categories fetched successfully."
    category_fetch_successful = "Category fetched successfully."
    category_create_successful = "Category created successfully."
    category_update_successful = "Category updated successfully."
    category_delete_successful = "Category deleted successfully."
    category_create_failed = "Failed to create category."
    category_update_failed = "Failed to update category."
    category_delete_failed = "Failed to delete category."

    all_regions_fetch_successful = "Regions fetched successfully."
    region_fetch_successful = "Region fetched successfully."
    region_create_failed = "Failed to create region"
    region_create_successful = "Region created successfully"
    region_update_successful = "Region updated successfully"
    region_update_failed = "Failed to update region"
    region_delete_successful = "Region deleted successfully"
    region_delete_failed = "Failed to delete region"

    all_recipes_fetch_successful = "Recipes fetched successfully."
    recipe_fetch_successful = "Recipe fetched successfully."
    recipe_create_successful = "Recipe created successfully."
    recipe_create_failed = "Failed to create recipe."
    recipe_update_successful = "Recipe updated successfully."
    recipe_update_failed = "Failed to update recipe."
    recipe_delete_successful = "Recipe deleted successfully."
    recipe_delete_failed = "Failed to delete recipe."
    fetch_todays_recipe_successful = "Today's recipe fetched successfully."

    all_ingredients_fetched_successfully = "Ingredients fetched successfully."
    ingredient_fetched_successfully = "Ingredient fetched successfully."
    ingredient_create_successful = "Ingredient created successfully."
    ingredient_create_failed = "Failed to create ingredient."
    ingredient_update_successful = "Ingredient updated successfully."
    ingredient_update_failed = "Failed to update ingredient."
    ingredient_delete_successful = "Ingredient deleted successfully."
    ingredient_delete_failed = "Failed to delete ingredient."

    all_reviews_fetched_successfully = "Reviews fetched successfully."
    reviews_not_found = "Reviews not found."
    review_fetched_successfully = "Review fetched successfully."
    review_not_found = "Review not found."
    reivew_create_successful = "Review created successfully."
    review_create_failed = "Failed to create review."
    review_update_successful = "Review updated successfully."
    review_update_failed = "Failed to update review."
    review_delete_successful = "Review deleted successfully."
    review_delete_failed = "Failed to delete review."

    cart_not_found_for_user = "Cart not found for the given user_id."
    cart_fetched_successfully = "Cart fetched successfully."
    cart_created_successfully = "Cart created successfully."
    cart_updated_successfully = "Cart updated successfully."
    cart_deleted_successfully = "Cart deleted successfully."
    cart_create_failed = "Failed to create cart."
    cart_update_failed = "Failed to update cart."
    cart_delete_failed = "Failed to delete cart."
